eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 1114
spring:
  application:
    name: ngcloud-ribbon
#  zipkin:
#      enabled: true
#      baseUrl: http://127.0.0.1:9411
