spring:
  application:
    name: ngcloud-gateway
#  cloud:
#    consul:
#      host: localhost
#      port: 8300
server:
  port: 1112

# 服务注册
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# 网关配置参数
zuul:
  routes:
    api-a.path: /api-a/**
    api-a.serviceId: ngcloud-client
    #api-a.serviceId: compute-service

#management:
#  security:
#    enabled: false